# Generated by Django 5.1.1 on 2026-03-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_movie_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theater',
            options={'ordering': ['name', 'show_time']},
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['movie', 'show_time'], name='theater_movie_show_idx'),
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['name', 'show_time'], name='theater_name_show_idx'),
        ),
    ]
